-- @description ReaSpect - context-sensitive inspector
-- @version 0.1.1-test
-- @author Davvo
-- @link https://forum.cockos.com/showthread.php?t=311132
-- @about Testing release. Requires REAPER 6.8+ and ReaImGui. Read EULA.md before use.
-- @changelog
--   Add per-track Notes with wrapped display, click-to-edit and project persistence.
--   Add draggable numeric fields, faster fade adjustments and consistent right-click defaults.
--   Reduce repeated menu redraws by grouping wheel edits and saving Notes after editing.
--   Improve Channel strip spacing, FX/Sends layout, numeric limits and selection-scoped undo.
--   Improve native meters, fader preference support, FX slot handling and FX search.
--   Remove redundant single-type event captions; retain mixed-selection summaries and tooltips.
-- @metapackage
-- @provides
--   [main] ../ReaSpect.lua > ReaSpect.lua
--   core/*.lua > ReaSpect/core/
--   widgets/*.lua > ReaSpect/widgets/
--   panels/*.lua > ReaSpect/panels/
--   inspectors/*.lua > ReaSpect/inspectors/
--   ../EULA.md > EULA.md

-- ReaPack manifest. The executable entry point is ../ReaSpect.lua.
