-- @description ReaSpect - context-sensitive inspector
-- @version 0.1.2-test
-- @author Davvo
-- @link https://forum.cockos.com/showthread.php?t=311132
-- @about Testing release. Requires REAPER 6.8+ and ReaImGui. Read EULA.md before use.
-- @changelog
--   Improve light-theme surfaces, FX/Sends slots, popups and selection contrast.
--   Make recording, monitoring, polarity and automation controls readable in light mode.
--   Keep icon-picker previews and labels readable when hovered or selected.
--   Remove decorative vertical separators from track and event headers.
-- @metapackage
-- @provides
--   [main] ../ReaSpect.lua > ReaSpect.lua
--   core/*.lua > ReaSpect/core/
--   widgets/*.lua > ReaSpect/widgets/
--   panels/*.lua > ReaSpect/panels/
--   inspectors/*.lua > ReaSpect/inspectors/
--   ../EULA.md > EULA.md

-- ReaPack manifest. The executable entry point is ../ReaSpect.lua.
